"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";

import { MantineProvider, ColorSchemeScript, AppShell, Group, Burger, Skeleton, createTheme, rem } from "@mantine/core";
import { useDisclosure } from "@mantine/hooks";
import { SideNav } from "@/components/Nav/SideNav";

import { AuthContextProvider, useAuth } from "../lib/authContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Notifications } from "@mantine/notifications";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();

const theme = createTheme({
  scale: 1,
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [opened, { toggle }] = useDisclosure();
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <QueryClientProvider client={queryClient}>
          <AuthContextProvider>
            <MantineProvider theme={theme}>
              <Notifications position="top-right" />
              <AppShell
                h="100%"
                header={{ height: 60 }}
                navbar={{ width: 300, breakpoint: "sm", collapsed: { mobile: !opened } }}
                padding="md"
              >
                <AppShell.Header>
                  <Group h="100%" px="md">
                    <Burger opened={opened} onClick={toggle} hiddenFrom="sm" size="sm" />
                    <div className="text-blue-700 text-xl font-extrabold">EquipmentGram</div>
                  </Group>
                </AppShell.Header>
                <AppShell.Navbar p="md">
                  <SideNav />
                </AppShell.Navbar>
                <AppShell.Main h="100%">{children}</AppShell.Main>

                {/* <AppShell.Footer p="md">Footer</AppShell.Footer> */}
              </AppShell>
            </MantineProvider>
          </AuthContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
